PACKAGE		= ec.tutorial.cointoss
MODNAME		= CoinToss

FILES.plu = \
	CoinMain.plu \
	CoinToss.plu \

include $(TOP)/E/makefiles/Defs.gmk

all: basics

clean: basic_clean

include $(TOP)/E/makefiles/Rules.gmk
