MODNAME	= ecgraphics
PACKAGE	= ec.misc.graphics

SAFETY_MODE = COMPUTE

FILES.javac = \
	Point2DInt.java \
	Point3D.java \
	RGB.java \

include $(TOP)/E/makefiles/Defs.gmk

.PHONY: all classes exports

all: basics

clean: basic_clean

include $(TOP)/E/makefiles/Rules.gmk
