include $(TOP)/E/makefiles/Defs.gmk

all:
#	cd ./crewdummy; $(MAKE)
	cd ./steward; $(MAKE)
	cd ./guest; $(MAKE)
	cd ./crew; $(MAKE)

clean:
	cd ./steward; $(MAKE) clean
	cd ./guest; $(MAKE) clean
	cd ./crew; $(MAKE) clean

