#!/bin/sh

# to create a process location server, run this command with the
# port number you want to listen at as the argument:
#
# pls_initial 1666
#
# Only do this once per port.  Use pls_restart to actually run it.
#

LOCATION_DIR=${PLS_LOCATION_DIR:-/home/eng/pls-location}
JAVA_DIR=${PLS_JAVA_DIR:-/home/eng/java-1.1.3/solaris/java-1.1.3}

if [ x$1 = x ]; then
	echo "You must specify the port to listen at."
	exit 1
fi

HostName=`uname -n | sed 's/\.communities\.com//'`
#FQDN="${HostName}.`domainname`" XXX anybody know how to get the domainname portably?
FQDN="${HostName}.communities.com"
Port=$1

base=${LOCATION_DIR}/${FQDN}_${Port}

if [ -f $base.props ]; then
    echo $base.props exists.
    echo "perhaps you want to use 'restart' instead."
    exit 1
fi

RELEASE_DIR=${PLS_RELEASE_DIR:-${base}.Release}

if [ ! -d ${RELEASE_DIR}/classes ]; then
    echo ${RELEASE_DIR}/classes: directory not found
    echo ${RELEASE_DIR} should be a symlink to where the classes can be found
    exit 1
fi

CLASSPATH=$JAVA_DIR/lib/classes.zip:$RELEASE_DIR/classes:$RELEASE_DIR/compute/classes:$RELEASE_DIR/crew/classes:$RELEASE_DIR/guest/classes:$RELEASE_DIR/steward/classes

LD_LIBRARY_PATH=/usr/lib:/usr/ucblib:$JAVA_DIR/lib/sparc:$RELEASE_DIR/lib:$RELEASE_DIR/solaris/lib:$RELEASE_DIR/native/solaris/lib

export JAVA_DIR CLASSPATH LD_LIBRARY_PATH

cat <<EOF > $base.props

RegisterWith=${base}
RegisterWithURLs=
SearchPath=${FQDN}:${Port}
checkpoint=${base}.evat
Controller=${base}.control
user.name=${Port}-PLS
killerhack=true
EncryptedLinks=false
TimeMachineMakerClass=ec.e.quake.TimeMachineMaker

EOF

cat <<EOF > $base.trace
Trace_ec.e.net.ProcessLocationServerHelper=debug
Trace_ec.e.quake.StableStore=debug
EOF


$JAVA_DIR/bin/java ec.e.boot.EBoot ec.app.net.BareProcessLocationServer -ECproperties $base.props -ECproperties $base.trace

echo
echo
echo "remember to push $base to ftp.communities.com /var/ftp/pub/pls-location"
echo " if you want others to be able to use this PLS"
echo
echo ftp ftp.communities.com
echo log in as someone with write permission...
echo cd /var/ftp/pub/pls-location
echo put $base
echo

