MODNAME	= ifcapptest
PACKAGE	= ec.ifc.app.test

SAFETY_MODE = CREW

FILES.javac = \
	ControlGroupTester.java \
	PageTurnerTester.java \
	TabTester.java \

include $(TOP)/E/makefiles/Defs.gmk

.PHONY: all classes exports

all: basics

clean: basic_clean

include $(TOP)/E/makefiles/Rules.gmk
