include $(TOP)/E/makefiles/Defs.gmk

all:
	cd $(TOP)/Support/ifc/app; $(MAKE)
	cd $(TOP)/Support/ifc/app/test; $(MAKE)
	cd $(TOP)/Support/ifc/stonelook; $(MAKE)

clean:
	cd $(TOP)/Support/ifc/app; $(MAKE) clean
	cd $(TOP)/Support/ifc/app/test; $(MAKE) clean
	cd $(TOP)/Support/ifc/stonelook; $(MAKE) clean

