MODNAME	= ecmisc
PACKAGE	= ec.misc

FILES.javac = \
	LineInputStream.java \
	LittleEndianInputStream.java

FILES.java = \
	Babysitter.java \
	InputSplitter.java \

include $(TOP)/E/makefiles/Defs.gmk

.PHONY: all classes exports

all: basics

clean: basic_clean

include $(TOP)/E/makefiles/Rules.gmk
