MODNAME	= ecnet
PACKAGE	= ec.net

SAFETY_MODE = CREW

FILES.java = \
	ByteArrayURLConnection.java \

include $(TOP)/E/makefiles/Defs.gmk

.PHONY: all classes exports

all: basics

clean: basic_clean

include $(TOP)/E/makefiles/Rules.gmk
