PACKAGE		= ec.plexamples.Tickets
MODNAME		= Tickets

FILES.java = j_Tickets.java \

FILES.plu = interfaces.plu \
ing_TicketHolderClient.plu \
ing_TicketHolderServer.plu \
ing_TicketManagerServer.plu \

include $(TOP)/E/makefiles/Defs.gmk

all: basics

clean: basic_clean

include $(TOP)/E/makefiles/Rules.gmk
