/* Generated By:JavaCC: Do not edit this line. EDocParserConstants.java */
package ec.edoc;

public interface EDocParserConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 6;
  int FORMAL_COMMENT = 7;
  int MULTI_LINE_COMMENT = 8;
  int ABSTRACT = 9;
  int BOOLEAN = 10;
  int BREAK = 11;
  int BYTE = 12;
  int CASE = 13;
  int CATCH = 14;
  int CHAR = 15;
  int CLASS = 16;
  int CONST = 17;
  int CONTINUE = 18;
  int _DEFAULT = 19;
  int DO = 20;
  int DOUBLE = 21;
  int ELSE = 22;
  int EXTENDS = 23;
  int FALSE = 24;
  int FINAL = 25;
  int FINALLY = 26;
  int FLOAT = 27;
  int FOR = 28;
  int GOTO = 29;
  int IF = 30;
  int IMPLEMENTS = 31;
  int IMPORT = 32;
  int INSTANCEOF = 33;
  int INT = 34;
  int INTERFACE = 35;
  int LONG = 36;
  int NATIVE = 37;
  int NEW = 38;
  int NULL = 39;
  int PACKAGE = 40;
  int PRIVATE = 41;
  int PROTECTED = 42;
  int PUBLIC = 43;
  int RETURN = 44;
  int SHORT = 45;
  int STATIC = 46;
  int SUPER = 47;
  int SWITCH = 48;
  int SYNCHRONIZED = 49;
  int THIS = 50;
  int THROW = 51;
  int THROWS = 52;
  int TRANSIENT = 53;
  int TRUE = 54;
  int TRY = 55;
  int VOID = 56;
  int VOLATILE = 57;
  int WHILE = 58;
  int ECATCH = 59;
  int ECLASS = 60;
  int EFALSE = 61;
  int EFORALL = 62;
  int EIF = 63;
  int EINTERFACE = 64;
  int EMETHOD = 65;
  int EORIF = 66;
  int EORWHEN = 67;
  int ETHROW = 68;
  int ETRUE = 69;
  int ETRY = 70;
  int EWHEN = 71;
  int EWHENEVER = 72;
  int FORWARD = 73;
  int INTEGER_LITERAL = 74;
  int DECIMAL_LITERAL = 75;
  int HEX_LITERAL = 76;
  int OCTAL_LITERAL = 77;
  int FLOATING_POINT_LITERAL = 78;
  int EXPONENT = 79;
  int CHARACTER_LITERAL = 80;
  int STRING_LITERAL = 81;
  int IDENTIFIER = 82;
  int LETTER = 83;
  int DIGIT = 84;
  int LPAREN = 85;
  int RPAREN = 86;
  int LBRACE = 87;
  int RBRACE = 88;
  int LBRACKET = 89;
  int RBRACKET = 90;
  int SEMICOLON = 91;
  int COMMA = 92;
  int DOT = 93;
  int ASSIGN = 94;
  int GT = 95;
  int LT = 96;
  int BANG = 97;
  int TILDE = 98;
  int HOOK = 99;
  int COLON = 100;
  int EQ = 101;
  int LE = 102;
  int GE = 103;
  int NE = 104;
  int SC_OR = 105;
  int SC_AND = 106;
  int INCR = 107;
  int DECR = 108;
  int PLUS = 109;
  int MINUS = 110;
  int STAR = 111;
  int SLASH = 112;
  int BIT_AND = 113;
  int BIT_OR = 114;
  int XOR = 115;
  int REM = 116;
  int LSHIFT = 117;
  int RSIGNEDSHIFT = 118;
  int RUNSIGNEDSHIFT = 119;
  int PLUSASSIGN = 120;
  int MINUSASSIGN = 121;
  int STARASSIGN = 122;
  int SLASHASSIGN = 123;
  int ANDASSIGN = 124;
  int ORASSIGN = 125;
  int XORASSIGN = 126;
  int REMASSIGN = 127;
  int LSHIFTASSIGN = 128;
  int RSIGNEDSHIFTASSIGN = 129;
  int RUNSIGNEDSHIFTASSIGN = 130;
  int SEND = 131;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<SINGLE_LINE_COMMENT>",
    "<FORMAL_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "\"abstract\"",
    "\"boolean\"",
    "\"break\"",
    "\"byte\"",
    "\"case\"",
    "\"catch\"",
    "\"char\"",
    "\"class\"",
    "\"const\"",
    "\"continue\"",
    "\"default\"",
    "\"do\"",
    "\"double\"",
    "\"else\"",
    "\"extends\"",
    "\"false\"",
    "\"final\"",
    "\"finally\"",
    "\"float\"",
    "\"for\"",
    "\"goto\"",
    "\"if\"",
    "\"implements\"",
    "\"import\"",
    "\"instanceof\"",
    "\"int\"",
    "\"interface\"",
    "\"long\"",
    "\"native\"",
    "\"new\"",
    "\"null\"",
    "\"package\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"return\"",
    "\"short\"",
    "\"static\"",
    "\"super\"",
    "\"switch\"",
    "\"synchronized\"",
    "\"this\"",
    "\"throw\"",
    "\"throws\"",
    "\"transient\"",
    "\"true\"",
    "\"try\"",
    "\"void\"",
    "\"volatile\"",
    "\"while\"",
    "\"ecatch\"",
    "\"eclass\"",
    "\"efalse\"",
    "\"eforall\"",
    "\"eif\"",
    "\"einterface\"",
    "\"emethod\"",
    "\"eorif\"",
    "\"eorwhen\"",
    "\"ethrow\"",
    "\"etrue\"",
    "\"etry\"",
    "\"ewhen\"",
    "\"ewhenever\"",
    "\"forward\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "\"<<\"",
    "\">>\"",
    "\">>>\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"%=\"",
    "\"<<=\"",
    "\">>=\"",
    "\">>>=\"",
    "\"<-\"",
  };

}
