MODNAME = edoc
PACKAGE = ec.edoc

include $(TOP)/E/makefiles/Defs.gmk

SAFETY_MODE = NON_VAT

FILES.javac = \
	ASCII_CharStream.java \
	ASCII_UCodeESC_CharStream.java \
	ASTAdditiveExpr.java \
	ASTAllocationExpression.java \
	ASTAnnotation.java \
	ASTArgumentList.java \
	ASTArguments.java \
	ASTArrayBrackets.java \
	ASTArrayDimensions.java \
	ASTAssignment.java \
	ASTAssignmentOperator.java \
	ASTBitwiseAndExpr.java \
	ASTBitwiseExclusiveOrExpr.java \
	ASTBitwiseInclusiveOrExpr.java \
	ASTBlock.java \
	ASTBlockStatement.java \
	ASTBooleanLiteral.java \
	ASTBreakStatement.java \
	ASTCastLookahead.java \
	ASTClassDeclaration.java \
	ASTCommand.java \
	ASTComment.java \
	ASTCompilationUnit.java \
	ASTConditionalAndExpr.java \
	ASTConditionalExpr.java \
	ASTConditionalOrExpr.java \
	ASTConstructorDeclaration.java \
	ASTContinueStatement.java \
	ASTDoStatement.java \
	ASTE_ClassDeclaration.java \
	ASTE_DistributionExpression.java \
	ASTE_IfStatement.java \
	ASTE_InterfaceDeclaration.java \
	ASTE_InterfaceMemberDeclaration.java \
	ASTE_MethodDeclaration.java \
	ASTE_SendStatement.java \
	ASTE_ThrowStatement.java \
	ASTE_TryStatement.java \
	ASTE_TypeDeclarationParameter.java \
	ASTE_WhenEverStatement.java \
	ASTE_WhenStatement.java \
	ASTEmptyStatement.java \
	ASTEqualityExpr.java \
	ASTExplicitConstructorInvocation.java \
	ASTExpression.java \
	ASTExtends.java \
	ASTFieldDeclaration.java \
	ASTForInit.java \
	ASTForStatement.java \
	ASTForUpdate.java \
	ASTFormalParameter.java \
	ASTFormalParameters.java \
	ASTIdentifier.java \
	ASTIfStatement.java \
	ASTImplements.java \
	ASTImportDeclaration.java \
	ASTInstanceOfExpr.java \
	ASTInterfaceDeclaration.java \
	ASTInterfaceMemberDeclaration.java \
	ASTLabeledStatement.java \
	ASTLiteral.java \
	ASTLocalVariableDeclaration.java \
	ASTMethodDeclaration.java \
	ASTMethodDeclarationLookahead.java \
	ASTModifier.java \
	ASTMulitplicativeExpr.java \
	ASTName.java \
	ASTNameList.java \
	ASTNullLiteral.java \
	ASTPackageDeclaration.java \
	ASTPostfixExpr.java \
	ASTPreDecrementExpression.java \
	ASTPreIncrementExpression.java \
	ASTPrimarySuffix.java \
	ASTPrimitiveType.java \
	ASTRelationalExpr.java \
	ASTResultType.java \
	ASTReturnStatement.java \
	ASTShiftExpr.java \
	ASTStatementExpression.java \
	ASTStatementExpressionList.java \
	ASTStaticInitializer.java \
	ASTSwitchLabel.java \
	ASTSwitchStatement.java \
	ASTSynchronizedStatement.java \
	ASTThrowStatement.java \
	ASTThrows.java \
	ASTTryStatement.java \
	ASTType.java \
	ASTVariableDeclarator.java \
	ASTVariableDeclaratorId.java \
	ASTVariableInitializer.java \
	ASTWhileStatement.java \
	ASTWord.java \
	AtCommand.java \
	AtParam.java \
	AtReturns.java \
	AtSee.java \
	AtThrows.java\
	AttributeInfo.java \
	AtDispatcher.java \
	ByteArray.java \
	ClassInfo.java \
	ClassInterfaceInfo.java \
	Comment.java \
	CommentParser.java \
	ConstPoolInfo.java \
	ConstantPool.java \
	ConstructorInfo.java \
	EDocParser.java \
	EDocParserConstants.java \
	EDocParserTokenManager.java \
	EClassInfo.java \
	EInterfaceInfo.java \
	EMethodInfo.java \
	ExceptionsAttributeInfo.java \
	FieldInfo.java \
	HTMLGenerator.java \
	IndexEntry.java \
	Info.java \
	InterfaceInfo.java \
	JavaClassInfo.java \
	JavaInterfaceInfo.java \
	JavaMethodInfo.java \
	MalformedASTException.java \
	MemberInfo.java \
	MemberNotSupportedException.java \
	MemberPoolInfo.java \
	MethodInfo.java \
	NameTypePair.java \
	Node.java \
	ParseError.java \
	PointerToInteger.java \
	SimpleNode.java \
	StaticInitialiserInfo.java \
	StringNotUnderstoodException.java \
	Token.java \
	TreeHelper.java \
	TreeWalker.java \
	TypeGuesser.java \
	TypeTable.java \
	VoidCodeAttributeInfo.java \
	estub.java \
	edoc.java

all: basics

clean: basic_clean

include $(TOP)/E/makefiles/Rules.gmk


#	CommentParser.java \
#	CommentParserConstants.java \
#	CommentParserTokenManager.java \
#	Information.java \
