/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>
/* Header for class ec_inspect_InspectableClass */

#ifndef _Included_ec_inspect_InspectableClass
#define _Included_ec_inspect_InspectableClass

typedef struct Classec_inspect_InspectableClass {
    char PAD;	/* ANSI C requires structures to have a least one member */
} Classec_inspect_InspectableClass;
HandleTo(ec_inspect_InspectableClass);

struct Hjava_lang_Class;
struct Hjava_lang_Object;
extern void ec_inspect_InspectableClass_setFieldValue(struct Hec_inspect_InspectableClass *,struct Hjava_lang_Class *,struct Hjava_lang_Object *,long,struct Hjava_lang_Object *);
extern void ec_inspect_InspectableClass_setDoubleFieldValue(struct Hec_inspect_InspectableClass *,struct Hjava_lang_Class *,struct Hjava_lang_Object *,long,double);
extern void ec_inspect_InspectableClass_setFloatFieldValue(struct Hec_inspect_InspectableClass *,struct Hjava_lang_Class *,struct Hjava_lang_Object *,long,float);
extern void ec_inspect_InspectableClass_setLongFieldValue(struct Hec_inspect_InspectableClass *,struct Hjava_lang_Class *,struct Hjava_lang_Object *,long,int64_t);
extern void ec_inspect_InspectableClass_setIntFieldValue(struct Hec_inspect_InspectableClass *,struct Hjava_lang_Class *,struct Hjava_lang_Object *,long,long);
extern void ec_inspect_InspectableClass_setShortFieldValue(struct Hec_inspect_InspectableClass *,struct Hjava_lang_Class *,struct Hjava_lang_Object *,long,short);
extern void ec_inspect_InspectableClass_setCharFieldValue(struct Hec_inspect_InspectableClass *,struct Hjava_lang_Class *,struct Hjava_lang_Object *,long,unicode);
extern void ec_inspect_InspectableClass_setByteFieldValue(struct Hec_inspect_InspectableClass *,struct Hjava_lang_Class *,struct Hjava_lang_Object *,long,char);
extern void ec_inspect_InspectableClass_setBooleanFieldValue(struct Hec_inspect_InspectableClass *,struct Hjava_lang_Class *,struct Hjava_lang_Object *,long,/*boolean*/ long);
extern HArrayOfObject *ec_inspect_InspectableClass_getFieldArrayValue(struct Hec_inspect_InspectableClass *,struct Hjava_lang_Class *,struct Hjava_lang_Object *,long);
extern HArrayOfDouble *ec_inspect_InspectableClass_getFieldDoubleArrayValue(struct Hec_inspect_InspectableClass *,struct Hjava_lang_Class *,struct Hjava_lang_Object *,long);
extern HArrayOfFloat *ec_inspect_InspectableClass_getFieldFloatArrayValue(struct Hec_inspect_InspectableClass *,struct Hjava_lang_Class *,struct Hjava_lang_Object *,long);
extern HArrayOfLong *ec_inspect_InspectableClass_getFieldLongArrayValue(struct Hec_inspect_InspectableClass *,struct Hjava_lang_Class *,struct Hjava_lang_Object *,long);
extern HArrayOfInt *ec_inspect_InspectableClass_getFieldIntArrayValue(struct Hec_inspect_InspectableClass *,struct Hjava_lang_Class *,struct Hjava_lang_Object *,long);
extern HArrayOfShort *ec_inspect_InspectableClass_getFieldShortArrayValue(struct Hec_inspect_InspectableClass *,struct Hjava_lang_Class *,struct Hjava_lang_Object *,long);
extern HArrayOfByte *ec_inspect_InspectableClass_getFieldByteArrayValue(struct Hec_inspect_InspectableClass *,struct Hjava_lang_Class *,struct Hjava_lang_Object *,long);
extern HArrayOfChar *ec_inspect_InspectableClass_getFieldCharArrayValue(struct Hec_inspect_InspectableClass *,struct Hjava_lang_Class *,struct Hjava_lang_Object *,long);
extern /*boolean*/ HArrayOfInt *ec_inspect_InspectableClass_getFieldBooleanArrayValue(struct Hec_inspect_InspectableClass *,struct Hjava_lang_Class *,struct Hjava_lang_Object *,long);
extern struct Hjava_lang_Object *ec_inspect_InspectableClass_getFieldValue(struct Hec_inspect_InspectableClass *,struct Hjava_lang_Class *,struct Hjava_lang_Object *,long);
struct Hjava_lang_String;
extern struct Hjava_lang_String *ec_inspect_InspectableClass_getFieldName(struct Hec_inspect_InspectableClass *,struct Hjava_lang_Class *,long);
extern struct Hjava_lang_String *ec_inspect_InspectableClass_getFieldSignature(struct Hec_inspect_InspectableClass *,struct Hjava_lang_Class *,long);
extern long ec_inspect_InspectableClass_getFieldModifiers(struct Hec_inspect_InspectableClass *,struct Hjava_lang_Class *,long);
extern long ec_inspect_InspectableClass_getNumberFields(struct Hec_inspect_InspectableClass *,struct Hjava_lang_Class *);
#endif
