/* DO NOT EDIT THIS FILE - it is machine generated */
#include <StubPreamble.h>

/* Stubs for class ec_inspect_InspectableClass */
/* SYMBOL: "ec_inspect_InspectableClass/setFieldValue(Ljava/lang/Class;Ljava/lang/Object;ILjava/lang/Object;)V", Java_ec_inspect_InspectableClass_setFieldValue_stub */
stack_item *Java_ec_inspect_InspectableClass_setFieldValue_stub(stack_item *_P_,struct execenv *_EE_) {
	extern void ec_inspect_InspectableClass_setFieldValue(void *,void *,void *,long,void *);
	(void) ec_inspect_InspectableClass_setFieldValue(NULL,((_P_[0].p)),((_P_[1].p)),((_P_[2].i)),((_P_[3].p)));
	return _P_;
}
/* SYMBOL: "ec_inspect_InspectableClass/setDoubleFieldValue(Ljava/lang/Class;Ljava/lang/Object;ID)V", Java_ec_inspect_InspectableClass_setDoubleFieldValue_stub */
stack_item *Java_ec_inspect_InspectableClass_setDoubleFieldValue_stub(stack_item *_P_,struct execenv *_EE_) {
	Java8 _t3;
	extern void ec_inspect_InspectableClass_setDoubleFieldValue(void *,void *,void *,long,double);
	(void) ec_inspect_InspectableClass_setDoubleFieldValue(NULL,((_P_[0].p)),((_P_[1].p)),((_P_[2].i)),GET_DOUBLE(_t3, _P_+3));
	return _P_;
}
/* SYMBOL: "ec_inspect_InspectableClass/setFloatFieldValue(Ljava/lang/Class;Ljava/lang/Object;IF)V", Java_ec_inspect_InspectableClass_setFloatFieldValue_stub */
stack_item *Java_ec_inspect_InspectableClass_setFloatFieldValue_stub(stack_item *_P_,struct execenv *_EE_) {
	extern void ec_inspect_InspectableClass_setFloatFieldValue(void *,void *,void *,long,float);
	(void) ec_inspect_InspectableClass_setFloatFieldValue(NULL,((_P_[0].p)),((_P_[1].p)),((_P_[2].i)),((_P_[3].f)));
	return _P_;
}
/* SYMBOL: "ec_inspect_InspectableClass/setLongFieldValue(Ljava/lang/Class;Ljava/lang/Object;IJ)V", Java_ec_inspect_InspectableClass_setLongFieldValue_stub */
stack_item *Java_ec_inspect_InspectableClass_setLongFieldValue_stub(stack_item *_P_,struct execenv *_EE_) {
	Java8 _t3;
	extern void ec_inspect_InspectableClass_setLongFieldValue(void *,void *,void *,long,int64_t);
	(void) ec_inspect_InspectableClass_setLongFieldValue(NULL,((_P_[0].p)),((_P_[1].p)),((_P_[2].i)),GET_INT64(_t3, _P_+3));
	return _P_;
}
/* SYMBOL: "ec_inspect_InspectableClass/setIntFieldValue(Ljava/lang/Class;Ljava/lang/Object;II)V", Java_ec_inspect_InspectableClass_setIntFieldValue_stub */
stack_item *Java_ec_inspect_InspectableClass_setIntFieldValue_stub(stack_item *_P_,struct execenv *_EE_) {
	extern void ec_inspect_InspectableClass_setIntFieldValue(void *,void *,void *,long,long);
	(void) ec_inspect_InspectableClass_setIntFieldValue(NULL,((_P_[0].p)),((_P_[1].p)),((_P_[2].i)),((_P_[3].i)));
	return _P_;
}
/* SYMBOL: "ec_inspect_InspectableClass/setShortFieldValue(Ljava/lang/Class;Ljava/lang/Object;IS)V", Java_ec_inspect_InspectableClass_setShortFieldValue_stub */
stack_item *Java_ec_inspect_InspectableClass_setShortFieldValue_stub(stack_item *_P_,struct execenv *_EE_) {
	extern void ec_inspect_InspectableClass_setShortFieldValue(void *,void *,void *,long,long);
	(void) ec_inspect_InspectableClass_setShortFieldValue(NULL,((_P_[0].p)),((_P_[1].p)),((_P_[2].i)),((_P_[3].i)));
	return _P_;
}
/* SYMBOL: "ec_inspect_InspectableClass/setCharFieldValue(Ljava/lang/Class;Ljava/lang/Object;IC)V", Java_ec_inspect_InspectableClass_setCharFieldValue_stub */
stack_item *Java_ec_inspect_InspectableClass_setCharFieldValue_stub(stack_item *_P_,struct execenv *_EE_) {
	extern void ec_inspect_InspectableClass_setCharFieldValue(void *,void *,void *,long,long);
	(void) ec_inspect_InspectableClass_setCharFieldValue(NULL,((_P_[0].p)),((_P_[1].p)),((_P_[2].i)),((_P_[3].i)));
	return _P_;
}
/* SYMBOL: "ec_inspect_InspectableClass/setByteFieldValue(Ljava/lang/Class;Ljava/lang/Object;IB)V", Java_ec_inspect_InspectableClass_setByteFieldValue_stub */
stack_item *Java_ec_inspect_InspectableClass_setByteFieldValue_stub(stack_item *_P_,struct execenv *_EE_) {
	extern void ec_inspect_InspectableClass_setByteFieldValue(void *,void *,void *,long,long);
	(void) ec_inspect_InspectableClass_setByteFieldValue(NULL,((_P_[0].p)),((_P_[1].p)),((_P_[2].i)),((_P_[3].i)));
	return _P_;
}
/* SYMBOL: "ec_inspect_InspectableClass/setBooleanFieldValue(Ljava/lang/Class;Ljava/lang/Object;IZ)V", Java_ec_inspect_InspectableClass_setBooleanFieldValue_stub */
stack_item *Java_ec_inspect_InspectableClass_setBooleanFieldValue_stub(stack_item *_P_,struct execenv *_EE_) {
	extern void ec_inspect_InspectableClass_setBooleanFieldValue(void *,void *,void *,long,long);
	(void) ec_inspect_InspectableClass_setBooleanFieldValue(NULL,((_P_[0].p)),((_P_[1].p)),((_P_[2].i)),((_P_[3].i)));
	return _P_;
}
/* SYMBOL: "ec_inspect_InspectableClass/getFieldArrayValue(Ljava/lang/Class;Ljava/lang/Object;I)[Ljava/lang/Object;", Java_ec_inspect_InspectableClass_getFieldArrayValue_stub */
stack_item *Java_ec_inspect_InspectableClass_getFieldArrayValue_stub(stack_item *_P_,struct execenv *_EE_) {
	extern void* ec_inspect_InspectableClass_getFieldArrayValue(void *,void *,void *,long);
	_P_[0].p = ec_inspect_InspectableClass_getFieldArrayValue(NULL,((_P_[0].p)),((_P_[1].p)),((_P_[2].i)));
	return _P_ + 1;
}
/* SYMBOL: "ec_inspect_InspectableClass/getFieldDoubleArrayValue(Ljava/lang/Class;Ljava/lang/Object;I)[D", Java_ec_inspect_InspectableClass_getFieldDoubleArrayValue_stub */
stack_item *Java_ec_inspect_InspectableClass_getFieldDoubleArrayValue_stub(stack_item *_P_,struct execenv *_EE_) {
	extern void* ec_inspect_InspectableClass_getFieldDoubleArrayValue(void *,void *,void *,long);
	_P_[0].p = ec_inspect_InspectableClass_getFieldDoubleArrayValue(NULL,((_P_[0].p)),((_P_[1].p)),((_P_[2].i)));
	return _P_ + 1;
}
/* SYMBOL: "ec_inspect_InspectableClass/getFieldFloatArrayValue(Ljava/lang/Class;Ljava/lang/Object;I)[F", Java_ec_inspect_InspectableClass_getFieldFloatArrayValue_stub */
stack_item *Java_ec_inspect_InspectableClass_getFieldFloatArrayValue_stub(stack_item *_P_,struct execenv *_EE_) {
	extern void* ec_inspect_InspectableClass_getFieldFloatArrayValue(void *,void *,void *,long);
	_P_[0].p = ec_inspect_InspectableClass_getFieldFloatArrayValue(NULL,((_P_[0].p)),((_P_[1].p)),((_P_[2].i)));
	return _P_ + 1;
}
/* SYMBOL: "ec_inspect_InspectableClass/getFieldLongArrayValue(Ljava/lang/Class;Ljava/lang/Object;I)[J", Java_ec_inspect_InspectableClass_getFieldLongArrayValue_stub */
stack_item *Java_ec_inspect_InspectableClass_getFieldLongArrayValue_stub(stack_item *_P_,struct execenv *_EE_) {
	extern void* ec_inspect_InspectableClass_getFieldLongArrayValue(void *,void *,void *,long);
	_P_[0].p = ec_inspect_InspectableClass_getFieldLongArrayValue(NULL,((_P_[0].p)),((_P_[1].p)),((_P_[2].i)));
	return _P_ + 1;
}
/* SYMBOL: "ec_inspect_InspectableClass/getFieldIntArrayValue(Ljava/lang/Class;Ljava/lang/Object;I)[I", Java_ec_inspect_InspectableClass_getFieldIntArrayValue_stub */
stack_item *Java_ec_inspect_InspectableClass_getFieldIntArrayValue_stub(stack_item *_P_,struct execenv *_EE_) {
	extern void* ec_inspect_InspectableClass_getFieldIntArrayValue(void *,void *,void *,long);
	_P_[0].p = ec_inspect_InspectableClass_getFieldIntArrayValue(NULL,((_P_[0].p)),((_P_[1].p)),((_P_[2].i)));
	return _P_ + 1;
}
/* SYMBOL: "ec_inspect_InspectableClass/getFieldShortArrayValue(Ljava/lang/Class;Ljava/lang/Object;I)[S", Java_ec_inspect_InspectableClass_getFieldShortArrayValue_stub */
stack_item *Java_ec_inspect_InspectableClass_getFieldShortArrayValue_stub(stack_item *_P_,struct execenv *_EE_) {
	extern void* ec_inspect_InspectableClass_getFieldShortArrayValue(void *,void *,void *,long);
	_P_[0].p = ec_inspect_InspectableClass_getFieldShortArrayValue(NULL,((_P_[0].p)),((_P_[1].p)),((_P_[2].i)));
	return _P_ + 1;
}
/* SYMBOL: "ec_inspect_InspectableClass/getFieldByteArrayValue(Ljava/lang/Class;Ljava/lang/Object;I)[B", Java_ec_inspect_InspectableClass_getFieldByteArrayValue_stub */
stack_item *Java_ec_inspect_InspectableClass_getFieldByteArrayValue_stub(stack_item *_P_,struct execenv *_EE_) {
	extern void* ec_inspect_InspectableClass_getFieldByteArrayValue(void *,void *,void *,long);
	_P_[0].p = ec_inspect_InspectableClass_getFieldByteArrayValue(NULL,((_P_[0].p)),((_P_[1].p)),((_P_[2].i)));
	return _P_ + 1;
}
/* SYMBOL: "ec_inspect_InspectableClass/getFieldCharArrayValue(Ljava/lang/Class;Ljava/lang/Object;I)[C", Java_ec_inspect_InspectableClass_getFieldCharArrayValue_stub */
stack_item *Java_ec_inspect_InspectableClass_getFieldCharArrayValue_stub(stack_item *_P_,struct execenv *_EE_) {
	extern void* ec_inspect_InspectableClass_getFieldCharArrayValue(void *,void *,void *,long);
	_P_[0].p = ec_inspect_InspectableClass_getFieldCharArrayValue(NULL,((_P_[0].p)),((_P_[1].p)),((_P_[2].i)));
	return _P_ + 1;
}
/* SYMBOL: "ec_inspect_InspectableClass/getFieldBooleanArrayValue(Ljava/lang/Class;Ljava/lang/Object;I)[Z", Java_ec_inspect_InspectableClass_getFieldBooleanArrayValue_stub */
stack_item *Java_ec_inspect_InspectableClass_getFieldBooleanArrayValue_stub(stack_item *_P_,struct execenv *_EE_) {
	extern void* ec_inspect_InspectableClass_getFieldBooleanArrayValue(void *,void *,void *,long);
	_P_[0].p = ec_inspect_InspectableClass_getFieldBooleanArrayValue(NULL,((_P_[0].p)),((_P_[1].p)),((_P_[2].i)));
	return _P_ + 1;
}
/* SYMBOL: "ec_inspect_InspectableClass/getFieldValue(Ljava/lang/Class;Ljava/lang/Object;I)Ljava/lang/Object;", Java_ec_inspect_InspectableClass_getFieldValue_stub */
stack_item *Java_ec_inspect_InspectableClass_getFieldValue_stub(stack_item *_P_,struct execenv *_EE_) {
	extern void* ec_inspect_InspectableClass_getFieldValue(void *,void *,void *,long);
	_P_[0].p = ec_inspect_InspectableClass_getFieldValue(NULL,((_P_[0].p)),((_P_[1].p)),((_P_[2].i)));
	return _P_ + 1;
}
/* SYMBOL: "ec_inspect_InspectableClass/getFieldName(Ljava/lang/Class;I)Ljava/lang/String;", Java_ec_inspect_InspectableClass_getFieldName_stub */
stack_item *Java_ec_inspect_InspectableClass_getFieldName_stub(stack_item *_P_,struct execenv *_EE_) {
	extern void* ec_inspect_InspectableClass_getFieldName(void *,void *,long);
	_P_[0].p = ec_inspect_InspectableClass_getFieldName(NULL,((_P_[0].p)),((_P_[1].i)));
	return _P_ + 1;
}
/* SYMBOL: "ec_inspect_InspectableClass/getFieldSignature(Ljava/lang/Class;I)Ljava/lang/String;", Java_ec_inspect_InspectableClass_getFieldSignature_stub */
stack_item *Java_ec_inspect_InspectableClass_getFieldSignature_stub(stack_item *_P_,struct execenv *_EE_) {
	extern void* ec_inspect_InspectableClass_getFieldSignature(void *,void *,long);
	_P_[0].p = ec_inspect_InspectableClass_getFieldSignature(NULL,((_P_[0].p)),((_P_[1].i)));
	return _P_ + 1;
}
/* SYMBOL: "ec_inspect_InspectableClass/getFieldModifiers(Ljava/lang/Class;I)I", Java_ec_inspect_InspectableClass_getFieldModifiers_stub */
stack_item *Java_ec_inspect_InspectableClass_getFieldModifiers_stub(stack_item *_P_,struct execenv *_EE_) {
	extern long ec_inspect_InspectableClass_getFieldModifiers(void *,void *,long);
	_P_[0].i = ec_inspect_InspectableClass_getFieldModifiers(NULL,((_P_[0].p)),((_P_[1].i)));
	return _P_ + 1;
}
/* SYMBOL: "ec_inspect_InspectableClass/getNumberFields(Ljava/lang/Class;)I", Java_ec_inspect_InspectableClass_getNumberFields_stub */
stack_item *Java_ec_inspect_InspectableClass_getNumberFields_stub(stack_item *_P_,struct execenv *_EE_) {
	extern long ec_inspect_InspectableClass_getNumberFields(void *,void *);
	_P_[0].i = ec_inspect_InspectableClass_getNumberFields(NULL,((_P_[0].p)));
	return _P_ + 1;
}
