PACKAGE		= ec.pl.examples.dieroll
MODNAME		= DieRoll

SAFETY_MODE = CREW

FILES.java = \
	DieRollEvent.java \
    IFCDieRollCrew.java \
	ConsoleDieRollCrew.java \

include $(TOP)/E/makefiles/Defs.gmk

all: basics

clean: basic_clean

include $(TOP)/E/makefiles/Rules.gmk
