MODNAME		= ifcconsole
PACKAGE		= ec.ifc.console

FILES.java = \
	ConsoleWindow.java \
	InputSplitter.java \

include $(TOP)/E/makefiles/Defs.gmk

all: basics

clean: basic_clean

include $(TOP)/E/makefiles/Rules.gmk
