MODNAME	= bdbi
PACKAGE	= ec.tools.bdbi
SAFETY_MODE = STEWARD

FILES.e = \
	Bdbi.e \
	Benchmark.e \
	BMethod.e \
	BConstruct.e \
	BTryCatch.e \
	BEmethod.e \
	BEwhen.e \
	BEtryCatch.e \
	BEclosure.e

include $(TOP)/E/makefiles/Defs.gmk

.PHONY: all classes

all: basics classes

clean: basic_clean

include $(TOP)/E/makefiles/Rules.gmk
