/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>
/* Header for class ec_url_crew_URLLauncher */

#ifndef _Included_ec_url_crew_URLLauncher
#define _Included_ec_url_crew_URLLauncher

typedef struct Classec_url_crew_URLLauncher {
    char PAD;   /* ANSI C requires structures to have a least one member */
} Classec_url_crew_URLLauncher;
HandleTo(ec_url_crew_URLLauncher);

#ifdef __cplusplus
extern "C" {
#endif
struct Hjava_lang_String;
extern long ec_url_crew_URLLauncher_nativeOpenURL(struct Hec_url_crew_URLLauncher *,struct Hjava_lang_String *);
#ifdef __cplusplus
}
#endif
#endif
