PACKAGE		= ec.pl.examples.dieroll
MODNAME		= DieRoll

SAFETY_MODE = GUEST

FILES.plu = \
	DieRollKind.plu \
	DieRollIngr.plu \
	DieRollPresence.plu \
	DieRollUnum.plu \
	Main.plu \

FILES.java = \
	DieRollState.java \

include $(TOP)/E/makefiles/Defs.gmk

all: basics

clean: basic_clean

include $(TOP)/E/makefiles/Rules.gmk
