PACKAGE		= ec.ui
MODNAME		= ec_uiconsole

FILES.java = \
	ConsoleWindow.java \
	InputSplitter.java \

include $(TOP)/E/makefiles/Defs.gmk

all: basics

clean: basic_clean

include $(TOP)/E/makefiles/Rules.gmk
