/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>
/* Header for class URLLauncher */

#ifndef _Included_URLLauncher
#define _Included_URLLauncher

typedef struct ClassURLLauncher {
    char PAD;   /* ANSI C requires structures to have a least one member */
} ClassURLLauncher;
HandleTo(URLLauncher);

#ifdef __cplusplus
extern "C" {
#endif
struct Hjava_lang_String;
__declspec(dllexport) long URLLauncher_OpenURL(struct HURLLauncher *,struct Hjava_lang_String *);
#ifdef __cplusplus
}
#endif
#endif
