SUBNAME = regexp
MODNAME =  tests/$(SUBNAME)
PACKAGE =  ec.tests.$(SUBNAME)

SAFETY_MODE = GUEST

include $(TOP)/E/makefiles/Defs.gmk

FILES.java = \
	TestRx.java

all: basics

run:
#	-$(JAVAEC) ec.tests.comm.HelloComm

include $(TOP)/E/makefiles/Rules.gmk

