MODNAME	= ecgraphics
PACKAGE	= ec.misc.graphics

SAFETY_MODE = CREW

FILES.javac = \
	ImageLoader.java \
	PPMLoader.java	 \
	BmpLoader.java 

include $(TOP)/E/makefiles/Defs.gmk

.PHONY: all classes exports

all: basics

clean: basic_clean

include $(TOP)/E/makefiles/Rules.gmk
