PACKAGE		= ec.pl.examples.dieroll
MODNAME		= DieRoll

SAFETY_MODE = STEWARD

FILES.java = \
    DieRollInterfaces.java \
	ConsoleDieRoll.java \
	DieRollSteward.java \

FILES.javac = \

include $(TOP)/E/makefiles/Defs.gmk

all: basics

clean: basic_clean

include $(TOP)/E/makefiles/Rules.gmk
