/* Generated By:JavaCC: Do not edit this line. CommentParserConstants.java */
package ec.edoc;

public interface CommentParserConstants {

  int EOF = 0;
  int OPEN_COMMENT = 7;
  int CLOSE_COMMENT = 8;
  int STARS = 9;
  int PARAM = 10;
  int RETURN = 11;
  int EXCEPTION = 12;
  int SEE = 13;
  int VERSION = 14;
  int AUTHOR = 15;
  int DEPRECATED = 16;
  int SINCE = 17;
  int TRUSTED = 18;
  int UNTRUSTED = 19;
  int NULL_OK = 20;
  int NULL_FATAL = 21;
  int INTEGER_LITERAL = 22;
  int DECIMAL_LITERAL = 23;
  int HEX_LITERAL = 24;
  int OCTAL_LITERAL = 25;
  int WORD = 26;
  int CHAR = 27;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"\\n\\r\"",
    "\"/**\"",
    "\"*/\"",
    "<STARS>",
    "\"@param\"",
    "\"@return\"",
    "\"@exception\"",
    "\"@see\"",
    "\"@version\"",
    "\"@author\"",
    "\"@deprecated\"",
    "\"@since\"",
    "\"trusted\"",
    "<UNTRUSTED>",
    "\"nullOK\"",
    "\"nullFatal\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<WORD>",
    "<CHAR>",
  };

}
