PACKAGE		= ec.pl.examples.web
MODNAME		= Web

SAFETY_MODE = GUEST

FILES.plu = \
	Web.plu \
	Main.plu \

FILES.javac = \

include $(TOP)/E/makefiles/Defs.gmk

all: basics

clean: basic_clean

include $(TOP)/E/makefiles/Rules.gmk
