PACKAGE		= ec.pl.examples.lamp
MODNAME		= Lamp

SAFETY_MODE = GUEST

FILES.plu = \
	Main.plu \
	Lamp.plu \

FILES.javac = \

include $(TOP)/E/makefiles/Defs.gmk

all: basics

clean: basic_clean

include $(TOP)/E/makefiles/Rules.gmk
