MODNAME	= lang
PACKAGE	= ec.e.lang

SAFETY_MODE = STEWARD

FILES.e = \
	EDouble.e \
	EFloat.e \
	EInteger.e \
	ELong.e \
	EPrintStream.e \
	EString.e \
	EObjectFuture.e \

include $(TOP)/E/makefiles/Defs.gmk

all: basics

clean: basic_clean

include $(TOP)/E/makefiles/Rules.gmk
