include $(TOP)/E/makefiles/Defs.gmk

all:
	cd ./compute; $(MAKE)
	cd ./crew; $(MAKE)
	cd ./steward; $(MAKE)

clean:
	cd ./compute; $(MAKE) clean
	cd ./crew; $(MAKE) clean
	cd ./steward; $(MAKE) clean
