#
# GNUmakefile for Pluribus runtime
#

SAFETY_MODE = CREW

MODNAME = plrun
PACKAGE = ec.pl.runtime

FILES.java = MagicUIPowerMaker.java

include $(TOP)/E/makefiles/Defs.gmk

.PHONY: all classes exports

all: basics 

clean: basic_clean

include $(TOP)/E/makefiles/Rules.gmk

