PACKAGE		= ec.pl.examples.simple
MODNAME		= Simple

FILES.plu = \
	ing_Simple.plu \
	unum_Simple.plu \

include $(TOP)/E/makefiles/Defs.gmk

all: basics

clean: basic_clean

include $(TOP)/E/makefiles/Rules.gmk
