
MODNAME	= cap
PACKAGE	= ec.e.cap

SAFETY_MODE = GUEST

FILES.java = \
	EEnvironment.java


include $(TOP)/E/makefiles/Defs.gmk

.PHONY: all classes exports

all: basics

clean: basic_clean

include $(TOP)/E/makefiles/Rules.gmk
