all:
		cd $(TOP)/E/tests/template; $(MAKE) 
		cd $(TOP)/E/tests/comm; $(MAKE) 
		cd $(TOP)/E/tests/compiler; $(MAKE) 
		cd $(TOP)/E/tests/db; $(MAKE) 
		cd $(TOP)/E/tests/dgc; $(MAKE) 
		cd $(TOP)/E/tests/hab; $(MAKE) 
		cd $(TOP)/E/tests/misc; $(MAKE) 
		cd $(TOP)/E/tests/run; $(MAKE) 
		cd $(TOP)/E/tests/timer; $(MAKE) 
		cd $(TOP)/E/tests/java/svm; $(MAKE) 
		cd $(TOP)/E/tests/java/gc; $(MAKE) 

runall:
		cd $(TOP)/E/tests/template; $(MAKE) run
		cd $(TOP)/E/tests/comm; $(MAKE) run
		cd $(TOP)/E/tests/compiler; $(MAKE) run
		cd $(TOP)/E/tests/db; $(MAKE) run
		cd $(TOP)/E/tests/dgc; $(MAKE) run
		cd $(TOP)/E/tests/hab; $(MAKE) run
		cd $(TOP)/E/tests/misc; $(MAKE) run
		cd $(TOP)/E/tests/run; $(MAKE) run
		cd $(TOP)/E/tests/timer; $(MAKE) run
		cd $(TOP)/E/tests/java/svm; $(MAKE) run
		cd $(TOP)/E/tests/java/gc; $(MAKE) run

clean:
		cd $(TOP)/E/tests/template; $(MAKE) clean
		cd $(TOP)/E/tests/comm; $(MAKE) clean
		cd $(TOP)/E/tests/compiler; $(MAKE) clean
		cd $(TOP)/E/tests/db; $(MAKE) clean
		cd $(TOP)/E/tests/dgc; $(MAKE) clean
		cd $(TOP)/E/tests/hab; $(MAKE) clean
		cd $(TOP)/E/tests/misc; $(MAKE) clean
		cd $(TOP)/E/tests/run; $(MAKE) clean
		cd $(TOP)/E/tests/timer; $(MAKE) clean
		cd $(TOP)/E/tests/java/svm; $(MAKE) clean
		cd $(TOP)/E/tests/java/gc; $(MAKE) clean

