MODNAME	= ifcutil
PACKAGE	= ec.ifc.util

FILES.javac = \
	NetscapeHashtable.java \
	NetscapeEnumeration.java \

include $(TOP)/E/makefiles/Defs.gmk

.PHONY: all classes exports

all: basics

clean: basic_clean

include $(TOP)/E/makefiles/Rules.gmk
