PACKAGE		= ec.pl.examples.lamp
MODNAME		= Lamp

SAFETY_MODE = CREW

FILES.java = \
	ConsoleCrew.java \

include $(TOP)/E/makefiles/Defs.gmk

all: basics

clean: basic_clean

include $(TOP)/E/makefiles/Rules.gmk
