PACKAGE		= ec.ui.util
MODNAME		= uiUtil

SAFETY_MODE = CREW

include $(TOP)/E/makefiles/Defs.gmk

all:
	$(MAKE) basics FILES.java=" \
				UpdateableTextWindow.java"


clean: basic_clean

include $(TOP)/E/makefiles/Rules.gmk
