
MODNAME	= plsping
PACKAGE	= ec.e.plsping

SAFETY_MODE = STEWARD

FILES.java = \
	PLSPing.java

include $(TOP)/E/makefiles/Defs.gmk

.PHONY: all classes exports

all: basics

clean: basic_clean

include $(TOP)/E/makefiles/Rules.gmk
