PACKAGE		= ec.pl.examples.lamp
MODNAME		= Lamp

SAFETY_MODE = STEWARD

FILES.java = \
	LampConsole.java \
    LampInterfaces.java \
	LampSteward.java \

FILES.javac = \

include $(TOP)/E/makefiles/Defs.gmk

all: basics

clean: basic_clean

include $(TOP)/E/makefiles/Rules.gmk
