MODNAME	= filter
PACKAGE	= ec.tools.filtereext
SAFETY_MODE = ECOMP

FILES.javac = \
	FilterEext.java

include $(TOP)/E/makefiles/Defs.gmk

.PHONY: all classes exports

all: basics

clean: basic_clean

include $(TOP)/E/makefiles/Rules.gmk
