PACKAGE		= ec.pl.examples.testbed
MODNAME		= TestBed

FILES.plu = \
	RefIng.plu \
	AUser_kind.plu \
	AUserIng_ingr.plu \
	ATestUnum.plu \
	BUser_kind.plu \
	BUserIng_ingr.plu \
	BTestUnum.plu \
	Main.plu \

include $(TOP)/E/makefiles/Defs.gmk

all: basics

clean: basic_clean

include $(TOP)/E/makefiles/Rules.gmk
