MODNAME	= ecutils
PACKAGE	= ec.util

SAFETY_MODE = STEWARD

include $(TOP)/E/makefiles/Defs.gmk

FILES.java = NativeSteward.java

all: basics

clean: basic_clean

include $(TOP)/E/makefiles/Rules.gmk

