#!/bin/sh
#
# Add C pre-processing to pluribus compiles
#
FILELIST_FILE=$1
OUTPUTDIR=$2
shift
shift
for i in $* ; do
  OUTFILE=$OUTPUTDIR/`basename $i`
  /usr/local/bin/cpp -lang-c++ -C -P $i $OUTFILE
  FILELIST="$FILELIST $OUTFILE"
done
echo $FILELIST > $FILELIST_FILE
