package ec.ez.ezvm;
import ec.ez.runtime.*;

/**
 *
 * Generated by the parser to represent a code block to be evaluated later.
 * While we could do this by creating a cluster of objects, we find it simpler
 * to use a specialized Expr to represent a block closure with no arguments which
 * can only respond to a single "run" verb.
 */
public class ThunkExpr extends Expr implements Script {
    private Expr myExpr;

    public ThunkExpr(Expr blockExpr) {
        myExpr = blockExpr;
    }

    public EZObject eval(Pov pov) throws Exception {
        return new EZImpl(pov.withScript(this));
    }

    public EZObject execute(Pov pov, String verb, EZObject[] args)
         throws Exception, Ejection {
       if(verb.equals("run"))
            return(myExpr.eval(pov));
         else
            throw new NotFoundException("Undefined verb: " + verb);
    }
}
