MODNAME	= ifccodable
PACKAGE	= ec.ifc.codable

FILES.javac = \
	WorldObjectState.java \
	WorldString.java \

include $(TOP)/E/makefiles/Defs.gmk

.PHONY: all classes exports

all: basics

clean: basic_clean

include $(TOP)/E/makefiles/Rules.gmk
