MODNAME		= ecerepsteward
PACKAGE		= ec.e.rep.steward
BUILDTYPE	= lib

DOCDIR       = $(TOP)/../../www-int/engineering/API_doc/javadoc 

SAFETY_MODE = STEWARD

FILES.java = \
	DataHolderInterfaces.java \
	DataHolderSteward.java \
	StandardRepositoryMaker.java \
	CertifiedCryptoHashBundle.java \

include $(TOP)/E/makefiles/Defs.gmk

.PHONY: all classes 

all: basics 

javadoc:
	javadoc -notree -noindex -d $(DOCDIR) $(FILES.javadoc)

clean: basic_clean

include $(TOP)/E/makefiles/Rules.gmk

