PACKAGE		= ec.pl.examples.web
MODNAME		= Web

SAFETY_MODE = STEWARD

FILES.java = \
	WebInterfaces.java \
	ConsoleWeb.java \
	WebSteward.java \

include $(TOP)/E/makefiles/Defs.gmk

all: basics

clean: basic_clean

include $(TOP)/E/makefiles/Rules.gmk
