
PACKAGE		= ec.e.stream
MODNAME		= stream

SAFETY_MODE = STEWARD

FILES.java = \
	StreamDB.java \
	PassByCopy.java

include $(TOP)/E/makefiles/Defs.gmk

.PHONY: all classes exports

all: basics

clean: basic_clean

include $(TOP)/E/makefiles/Rules.gmk

