include $(TOP)/E/makefiles/Defs.gmk

all:
	-cd $(TOP)/Pluribus/Examples/CoinToss; $(MAKE)
	-cd $(TOP)/Pluribus/Examples/DieRoll; $(MAKE)
	-cd $(TOP)/Pluribus/Examples/Lamp; $(MAKE)
#	-cd $(TOP)/Pluribus/Examples/Simple/Simple1; $(MAKE)
#	-cd $(TOP)/Pluribus/Examples/Simple/Simple2; $(MAKE)
#	-cd $(TOP)/Pluribus/Examples/TestBed; $(MAKE)
#	-cd $(TOP)/Pluribus/Examples/Web; $(MAKE)

clean:
	-cd $(TOP)/Pluribus/Examples/CoinToss; $(MAKE) clean
	-cd $(TOP)/Pluribus/Examples/DieRoll; $(MAKE) clean
	-cd $(TOP)/Pluribus/Examples/Lamp; $(MAKE) clean
#	-cd $(TOP)/Pluribus/Examples/Simple/Simple1; $(MAKE) clean
#	-cd $(TOP)/Pluribus/Examples/Simple/Simple2; $(MAKE) clean
#	-cd $(TOP)/Pluribus/Examples/TestBed; $(MAKE) clean
#	-cd $(TOP)/Pluribus/Examples/Web; $(MAKE) clean


